apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
  annotations:
    description: "Switch selector version between blue and green to route traffic instantaneously"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8081
  selector:
    app: bankapp
    version: blue # Change to "green" for instant zero-downtime switch
